# Generated by Django 4.0 on 2024-04-22 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('time_create', models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 22, 9, 35, 26, 966269), verbose_name='Дата и время обнаружения происшествия')),
                ('time_start', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время принятия решения')),
                ('time_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время ликвидирования происшествия')),
                ('taken_measures', models.CharField(blank=True, max_length=255, null=True, verbose_name='Принятые меры по ликвидации')),
            ],
            options={
                'verbose_name': 'Происшествие',
                'verbose_name_plural': 'Происшествия',
                'permissions': [('Incidents.incidents_add', 'Добавление происшествий'), ('Incidents.incidents_change', 'Изменение происшествий'), ('Incidents.incidents_delete', 'Удаление происшествий'), ('Incidents.incidents_id', 'Просмотр происшествия'), ('Incidents.incidents_map', 'Просмотр всех происшествий на карте'), ('Incidents.incidents_all', 'Просмотр всех происшествий в таблице')],
            },
        ),
    ]
